### ISSUE TITLE
Interactive Inventory Tool Lossing Access to the Alma API

### ISSUE THREAD

**Issue by AdrienneRadzvickas** [CARLI/AlmaInventory#1]
2. Some staff have reported the Alma Interactive Inventory Scanning Tool appears to lose access to the Alma API after a certain number of scans. It still records the barcode, but cannot pull the other details. This is evident beginning in row 16 of the file exported from Alma Interactive Inventory Scanning Tool.

**Comment by gibsonjc** [comment]
RT #129738

**Comment by cedelis** [comment]
Alphanumeric barcodes were not being supported properly.

Bugfix:

https://github.com/CARLI/AlmaInventory/commit/2031966101f15a6963987678be2bb158e8682134
