### ISSUE TITLE
Interactive Inventory Tool - Make Sound When There Is a Problem

### ISSUE THREAD

**Issue by AdrienneRadzvickas** [CARLI/AlmaInventory#2]
EIU has done some testing with the Alma Interactive Inventory Scanning Tool, and overall it fits our needs very well. We do have one request: Is it possible to have the system make a sound in addition to the color change on the screen to show problems? We use a small Chromebook for inventory, and it is very difficult to catch the color change from red to black on the call number for items that are out of order.

I've spoked with Joe Hall-Ingram at UIUC's Grainger and he would also like to have a sound play when the system finds a problem or an item is out of order.

**Comment by gibsonjc** [comment]
RT #129603

**Comment by cedelis** [comment]
Sound optional beep whenever status is not 'PASS' or when call number is out of order

commits:
e40ad460f74d7bd236da1d3255a800dab91f78e5
e9b9e69c094ea8a74683e9679b99ff918dbbc1a5
